apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "chart.fullname" . }}-metrics-certs
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ include "chart.fullname" . }}-SERVICE_NAME.SERVICE_NAMESPACE.svc'
  - '{{ include "chart.fullname" . }}-SERVICE_NAME.SERVICE_NAMESPACE.svc.{{ .Values.kubernetesClusterDomain
    }}'
  issuerRef:
    kind: Issuer
    name: '{{ include "chart.fullname" . }}-selfsigned-issuer'
  secretName: metrics-server-cert