apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "application-rbac-validator.fullname" . }}-serving-cert
  labels:
  {{- include "application-rbac-validator.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ include "application-rbac-validator.fullname" . }}-SERVICE_NAME.SERVICE_NAMESPACE.svc'
  - '{{ include "application-rbac-validator.fullname" . }}-SERVICE_NAME.SERVICE_NAMESPACE.svc.{{
    .Values.kubernetesClusterDomain }}'
  issuerRef:
    kind: Issuer
    name: '{{ include "application-rbac-validator.fullname" . }}-selfsigned-issuer'
  secretName: webhook-server-cert