apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "application-rbac-validator.fullname" . }}-leader-election-rolebinding
  labels:
  {{- include "application-rbac-validator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "application-rbac-validator.fullname" . }}-leader-election-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "application-rbac-validator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'