apiVersion: v1
kind: Service
metadata:
  name: {{ include "application-rbac-validator.fullname" . }}-metrics-service
  labels:
    control-plane: controller-manager
  {{- include "application-rbac-validator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    app.kubernetes.io/name: application-rbac-validator
    control-plane: controller-manager
  {{- include "application-rbac-validator.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 }}