apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "application-rbac-validator.fullname" . }}-metrics-auth-rolebinding
  labels:
  {{- include "application-rbac-validator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "application-rbac-validator.fullname" . }}-metrics-auth-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "application-rbac-validator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'