apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "application-rbac-validator.fullname" . }}-metrics-reader
  labels:
  {{- include "application-rbac-validator.labels" . | nindent 4 }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get