apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "application-rbac-validator.fullname" . }}-controller-manager
  labels:
  {{- include "application-rbac-validator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}